[2025-04-27T00:00:02.835+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-27T00:00:02.880+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earth_monitoring_system.fetch_air_quality_data scheduled__2025-04-26T00:00:00+00:00 [queued]>
[2025-04-27T00:00:02.894+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earth_monitoring_system.fetch_air_quality_data scheduled__2025-04-26T00:00:00+00:00 [queued]>
[2025-04-27T00:00:02.894+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-27T00:00:02.921+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): fetch_air_quality_data> on 2025-04-26 00:00:00+00:00
[2025-04-27T00:00:02.930+0000] {standard_task_runner.py:57} INFO - Started process 394 to run task
[2025-04-27T00:00:02.933+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'earth_monitoring_system', 'fetch_air_quality_data', 'scheduled__2025-04-26T00:00:00+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/earth_monitoring_dag.py', '--cfg-path', '/tmp/tmpdvidiaul']
[2025-04-27T00:00:02.935+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask fetch_air_quality_data
[2025-04-27T00:00:02.983+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-27T00:00:03.103+0000] {task_command.py:410} INFO - Running <TaskInstance: earth_monitoring_system.fetch_air_quality_data scheduled__2025-04-26T00:00:00+00:00 [running]> on host 4a0d29ea382b
[2025-04-27T00:00:03.156+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-27T00:00:03.369+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='earth_monitoring_system' AIRFLOW_CTX_TASK_ID='fetch_air_quality_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-26T00:00:00+00:00'
[2025-04-27T00:00:03.370+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-27T00:00:03.370+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/airflow/data_collection && python fetch_openaq.py']
[2025-04-27T00:00:03.377+0000] {subprocess.py:86} INFO - Output:
[2025-04-27T00:00:03.640+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-27T00:00:03.642+0000] {subprocess.py:93} INFO -   File "fetch_openaq.py", line 9, in <module>
[2025-04-27T00:00:03.643+0000] {subprocess.py:93} INFO -     from openaq import OpenAQ
[2025-04-27T00:00:03.643+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'openaq'
[2025-04-27T00:00:03.647+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-27T00:00:03.691+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 211, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-27T00:00:03.694+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=earth_monitoring_system, task_id=fetch_air_quality_data, execution_date=20250426T000000, start_date=20250427T000002, end_date=20250427T000003
[2025-04-27T00:00:03.723+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 13 for task fetch_air_quality_data (Bash command failed. The command returned a non-zero exit code 1.; 394)
[2025-04-27T00:00:03.731+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-04-27T00:00:03.796+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
