[2025-04-26T21:27:27.473+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: earth_monitoring_system.fetch_air_quality_data manual__2025-04-26T21:27:25.469969+00:00 [queued]>
[2025-04-26T21:27:27.483+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: earth_monitoring_system.fetch_air_quality_data manual__2025-04-26T21:27:25.469969+00:00 [queued]>
[2025-04-26T21:27:27.484+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-04-26T21:27:27.504+0000] {taskinstance.py:1327} INFO - Executing <Task(BashOperator): fetch_air_quality_data> on 2025-04-26 21:27:25.469969+00:00
[2025-04-26T21:27:27.506+0000] {standard_task_runner.py:57} INFO - Started process 254 to run task
[2025-04-26T21:27:27.509+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'earth_monitoring_system', 'fetch_air_quality_data', 'manual__2025-04-26T21:27:25.469969+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/earth_monitoring_dag.py', '--cfg-path', '/tmp/tmp4pld4k46']
[2025-04-26T21:27:27.510+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask fetch_air_quality_data
[2025-04-26T21:27:27.551+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-26T21:27:27.662+0000] {task_command.py:410} INFO - Running <TaskInstance: earth_monitoring_system.fetch_air_quality_data manual__2025-04-26T21:27:25.469969+00:00 [running]> on host d522fce2db24
[2025-04-26T21:27:27.929+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='earth_monitoring_system' AIRFLOW_CTX_TASK_ID='fetch_air_quality_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-26T21:27:25.469969+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-26T21:27:25.469969+00:00'
[2025-04-26T21:27:27.930+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-26T21:27:27.932+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/airflow/data_collection && python fetch_openaq.py']
[2025-04-26T21:27:27.938+0000] {subprocess.py:86} INFO - Output:
[2025-04-26T21:27:28.348+0000] {subprocess.py:93} INFO - 2025-04-26 21:27:28,347 - INFO - Starting data collection from OpenAQ
[2025-04-26T21:27:28.352+0000] {subprocess.py:93} INFO - 2025-04-26 21:27:28,349 - INFO - Fetching data from OpenAQ API with limit 1000
[2025-04-26T21:27:29.069+0000] {subprocess.py:93} INFO - 2025-04-26 21:27:29,069 - ERROR - Error fetching data from OpenAQ: 410 Client Error: Gone for url: https://api.openaq.org/v2/latest?limit=1000&has_geo=true
[2025-04-26T21:27:29.071+0000] {subprocess.py:93} INFO - 2025-04-26 21:27:29,070 - INFO - Data collection completed
[2025-04-26T21:27:29.086+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-26T21:27:29.192+0000] {taskinstance.py:1350} INFO - Marking task as SUCCESS. dag_id=earth_monitoring_system, task_id=fetch_air_quality_data, execution_date=20250426T212725, start_date=20250426T212727, end_date=20250426T212729
[2025-04-26T21:27:29.248+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2025-04-26T21:27:29.309+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
